#cloud-config
ssh_pwauth: no
users:
  - name: user
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [sudo]
    shell: /bin/bash
    ssh-authorized-keys:
      - "${SSH_PUBLIC_KEY}"

package_update: true
packages:
  - curl
  - ca-certificates
  - unattended-upgrades 

runcmd:
  - curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
  - chmod +x /tmp/get-docker.sh
  - sh /tmp/get-docker.sh
  - usermod -aG docker user
