name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Select the Terraform action'
        required: true
        default: 'plan'
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    env:
      TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
      TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.3

    - name: Set up Yandex Cloud service account key
      run: |
        echo "${{ secrets.YC_AUTHORIZED_KEY }}" | base64 -d > ./authorized_key.json

    - name: Initialize Terraform
      run: terraform init
        -backend-config="bucket=$S3_BUCKET"
        -backend-config="access_key=$ACCESS_KEY"
        -backend-config="secret_key=$SECRET_KEY"
      env:
        S3_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    - name: Validate Terraform
      run: terraform validate

    - name: Terraform Plan
      if: ${{ github.event.inputs.action == 'plan' }}
      run: terraform plan

    - name: Terraform Apply
      if: ${{ github.event.inputs.action == 'apply' }}
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: terraform destroy -auto-approve


# Описание workflow
# Шаг 	Описание
# Checkout code 	Получение кода из репозитория (использует actions/checkout@v2)
# Setup Terraform 	Установка Terraform версии 1.8.3 (использует hashicorp/setup-terraform@v2)
# Set up Yandex Cloud service account key 	Создание файла авторизации для Yandex Cloud из secrets
# Initialize Terraform 	Инициализация Terraform с настройками бэкенда
# Terraform Plan 	Выполнение terraform plan (если выбрано действие 'plan')
# Terraform Apply 	Выполнение terraform apply -auto-approve (если выбрано действие 'apply')
# Terraform Destroy 	Выполнение terraform destroy -auto-approve (если выбрано действие 'destroy')
